repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0   # latest stable release
    hooks:
      - id: black
        language_version: python3
        # If black reformats files, commit will fail with a message

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2   # latest mypy mirror release
    hooks:
      - id: mypy
